#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Long;
use Socket;
use File::Copy;

my @CONFIG_VARIABLES = (
    'HOST_DNS_ADDRESS',
    'GLASSFISH_DIRECTORY',
    'MAIL_SERVER',
    'RSERVE_HOST',
    'RSERVE_PORT',
    'RSERVE_USER',
    'RSERVE_PASSWORD',
    'SOLR_HOST',
    'SOLR_PORT',
);


my %CONFIG_DEFAULTS = (
    'HOST_DNS_ADDRESS',    'localhost',
    'GLASSFISH_DIRECTORY', '/usr/local/glassfish4',
    'MAIL_SERVER',         '',
    'RSERVE_HOST',     'localhost',
    'RSERVE_PORT',     6311,
    'RSERVE_USER',     'rserve',
    'RSERVE_PASSWORD', 'rserve'
);

# Config always from ENV
for my $ENTRY (@CONFIG_VARIABLES) {
    if (!$ENV{$ENTRY}) {
    	$ENV{$ENTRY} = $CONFIG_DEFAULTS{$ENTRY};
    } else {
    	$CONFIG_DEFAULTS{$ENTRY} = $ENV{$ENTRY};
    }
}

print "\nInitializing Postgres\n";
system("./init-postgres");

print "\nInitializing Glassfish\n";
system("./init-glassfish");

print "\nInitializing Dataverse\n";
system("./setup-all.sh");

system ("curl -s -X PUT -d " . $CONFIG_DEFAULTS{'SOLR_HOST'} . ":" . $CONFIG_DEFAULTS{'SOLR_PORT'} . " http://localhost:8080/api/admin/settings/:SolrHostColonPort");

if ( defined $ENV{"TWORAVENS_URL"} && defined $ENV{"TWORAVENS_PORT_80_TCP_PORT"} ) {
    print "Using TwoRavens at " . $ENV{'TWORAVENS_URL'} . "\n";
    system ("curl -s -X PUT -d " . $ENV{'TWORAVENS_URL'} . "/dataexplore/gui.html" . " http://localhost:8080/api/admin/settings/:TwoRavensUrl");
}

print "\nRestarting Glassfish -- this could take a minute\n";
system("./restart-glassfish");
