from 	ubuntu:14.04

run 	apt-get -y update && \
	apt-get -y install gzip maven postgresql postgresql-contrib jq curl \
		git maven && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#
# add the dependencies, install, then delete them
#
#add 	dependencies /tmp/dependencies
#run 	unzip /tmp/dependencies/glassfish-4.1.zip
#run	tar xf /tmp/dependencies/solr-4.6.0-src.tgz
#run	mkdir -p /usr/java && tar xf /tmp/dependencies/jdk-8u60-linux-x64.tar.gz -C /usr/java 
#
# FIXME netbeans wants X for setup, leave off for now
#run	sh /dependencies/netbeans-8.0.2-javase-linux.sh
#
#run	rm -rf /tmp/dependencies
#run	git clone https://github.com/IQSS/dataverse.git

EXPOSE 80 443 8993 8080 8181
